---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - phpAdminValues.yaml
  - release.yaml
  - phpMyAdmin.yaml
  - ingress.yaml

configMapGenerator:
  - name: db-init
    files:
      - init_script.sh
  - name: start-up
    files:
      - start_script.sh
  - name: mysql-values
    files:
      - values.yaml
    
generatorOptions:
  disableNameSuffixHash: true
