---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpadmin-values
data:
  values.yaml: |
    global:
      security:
        allowInsecureImages: true
    #image:
    #  registry: 000000000000.dkr.ecr.us-east-1.amazonaws.com
    #  repository: services/phpmyadmin
    #  tag: latest
    db:
      host: 'mysql'

