---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-awspca:issuer-access
rules:
  - apiGroups: ["awspca.cert-manager.io"]
    resources: ["awspcaclusterissuers", "awspcaclusterissuers/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-awspca:issuer-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-awspca:issuer-access
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager

