apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pv.yaml
  - pvc.yaml
  - release.yaml

configMapGenerator:
  - name: nexus-values
    files:
      - values.yaml
    behavior: create
generatorOptions:
  disableNameSuffixHash: true
