apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: datadog
spec:
  releaseName: release
  chart:
    spec:
      chart: datadog
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: flux-system
      version: "3.19.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    targetSystem: "linux"
    clusterAgent:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 200m
          memory: 256Mi
    agents:
      enabled: true
      containers:
        agent:
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 256Mi
    datadog:
      apiKey: ""
      apiKeyExistingSecret:  # <DATADOG_API_KEY_SECRET>
      appKey: ""
      appKeyExistingSecret:  # <DATADOG_APP_KEY_SECRET>
      hostVolumeMountPropagation: None
      clusterName: ""
      site: datadoghq.com
      logLevel: INFO
      kubeStateMetricsCore:
        enabled: false
      clusterChecks:
        enabled: false
      collectEvents: false
      processAgent:
          enabled: false
          processCollection: false
      leaderElection: true
      logs:
        enabled: true
        containerCollectAll: false
        containerCollectUsingFiles: true
        autoMultiLineDetection: false
      apm:
        enabled: false
      env:
        - name: 'DD_LOGS_CONFIG_K8S_CONTAINER_USE_FILE'
          value: true
      prometheusScrape:
        enabled: false
        serviceEndpoints: false
