---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secrets.${app}.${name}
  namespace: ${env}-${app}
spec:
  interval: 1m
  timeout: 2m
  releaseName: secrets.${name}
  targetNamespace: flux-system
  install:
    remediation:
      retries: 3
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
      remediateLastFailure: true
    cleanupOnFail: true
    force: false
  uninstall:
    keepHistory: false
  chart:
    spec:
      chart: secrets
      sourceRef:
        kind: HelmRepository
        name: demo-platform
        namespace: flux-system
      version: 0.1.6
  values:
    name: ${env}.${app}.${name}
    keys: ${keys}
    encoding: ${encoding}
    length: ${length}
