---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 12h
  url: https://charts.jetstack.io

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: awspca
  namespace: flux-system
spec:
  interval: 12h
  url: https://cert-manager.github.io/aws-privateca-issuer
