---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: devtron
  namespace: flux-system
spec:
  interval: 10h
  # url: https://jfelten.github.io/wireguard-helm/
  url: http://helm.devtron.ai/
