---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mittwald
  namespace: flux-system
spec:
  interval: 10h
  # url: https://github.com/mittwald/kubernetes-secret-generator
  url: https://helm.mittwald.de

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: secret-generator
  namespace: flux-system
spec:
  type: oci
  interval: 10h
  url: oci://ghcr.io/sap/secret-generator-helm

#---
#apiVersion: source.toolkit.fluxcd.io/v1
#kind: OCIRepository
#metadata:
#  name: secret-generator
#  namespace: flux-system
#spec:
#  interval: 120m0s
#  provider: generic
#  url: oci://ghcr.io/sap/secret-generator-helm
#  ref:
#    tag: "v0.4.61"
#  verify:
#    provider: cosign
