---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: wireguard
  namespace: flux-system
spec:
  interval: 10h
  # url: https://jfelten.github.io/wireguard-helm/
  url: https://bryopsida.github.io/wireguard-chart
