# complete example of clone source type of foreach declaration 
# that clones the source Secret into a list of matching existing
# namespaces which is stored as a comma-separated string in a ConfigMap
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: foreach-clone
spec:
  rules:
  - match:
      any:
      - resources:
          kinds:
          - ConfigMap
    name: k-kafka-address
    context:
    - name: configmapns
      variable:
        jmesPath: request.object.metadata.namespace
    preconditions:
      any:
      - key: '{{configmapns}}'
        operator: Equals
        value: 'default'
    generate:
      generateExisting: false
      synchronize: true
      foreach:
        - list: request.object.data.namespaces | split(@, ',')
          context:
          - name: ns
            variable:
              jmesPath: element
          preconditions:
            any:
            - key: '{{ ns }}'
              operator: AnyIn
              value:
              - foreach-ns-1
          apiVersion: v1
          kind: Secret
          name: cloned-secret-{{ elementIndex }}-{{ ns }}
          namespace: '{{ ns }}'
          clone:
            namespace: default
            name: source-secret

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: default-deny
  namespace: default
data:
  namespaces: foreach-ns-1,foreach-ns-2
