---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: allure-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  volumeName: allure-persistent-volume
  storageClassName: ""
