---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: devops
spec:
  releaseName: external-secrets
  targetNamespace: devops
  values:
    serviceAccount:
      annotations:
       eks.amazonaws.com/role-arn: ${external_secrets_sa_role_arn}

    # run all components at `infra` pool
    certController:
      nodeSelector:
        pool: infra
      tolerations:
      - effect: NoSchedule
        key: pool
        operator: Equal
        value: infra

    webhook:
      nodeSelector:
        pool: infra
      tolerations:
      - effect: NoSchedule
        key: pool
        operator: Equal
        value: infra

    nodeSelector:
      pool: infra
    tolerations:
    - effect: NoSchedule
      key: pool
      operator: Equal
      value: infra