---
apiVersion: 'v1'
kind: 'ConfigMap'
metadata:
  name: 'redis-cluster-values'
  # namespace: 'flux-system'
data:
  values.yaml: |
    persistence:
      storageClass: 'gp2'
    redis:
      replicaCount: 1
      tolerations:
        - key: 'pool'
          value: 'infra'
          effect: 'NoSchedule'
    cluster:
      init: true
      nodes: 1
