---
global:
  security:
    allowInsecureImages: true
auth:
  password: ${REDIS_PASSWORD}
  #existingSecret: ${pref}-redis-passwd
  #existingSecretPasswordKey: REDIS_PASSWORD
image:
  registry: 000000000000.dkr.ecr.us-east-1.amazonaws.com
  repository: tools/redis
  tag: 1.0.198
master:
  replicaCount: 1
  persistence:
    storageClass: gp2
replica:
  replicaCount: 1
  persistence:
    storageClass: gp2
