{
 "title": "Application monitoring",
 "tags": [
  "infra",
  "monitoring"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(kube_service_info{cluster=\"$cluster\", namespace=\"$namespace\"},service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Restarts",
   "type": "gauge",
   "description": "Total restart counts of all pods in service $service.\nBased on kube_pod_container_status_restarts_total",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  kube_pod_container_status_restarts_total{\n    cluster=\"$cluster\",\n    namespace=\"$namespace\",\n    pod=~\"$service.*\"\n  }\n  * on(pod, namespace) group_left()\n  kube_pod_status_phase{phase=\"Running\", cluster=\"$cluster\", namespace=\"$namespace\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU utilization of all pods matching the selected service ($service) in namespace $namespace on cluster $cluster. Uses 5m rate of container_cpu_usage_seconds_total with pod name matching \"$service.*\".",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_cpu_usage_seconds_total{\n    cluster=\"$cluster\",\n    namespace=\"$namespace\",\n    pod=~\"$service.*\"\n  }[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel 5xx Error RateTitle",
   "type": "timeseries",
   "description": "This panel displays the HTTP 5xx Error Rate (%) for the selected cluster, namespace, and service.\nIt measures the proportion of all incoming requests that resulted in server-side errors.\n\nDefinition:\n5xx errors represent failures caused by the application or upstream components (not client issues).\nA rising value indicates backend instability, timeouts, crashes, or overload conditions.\n",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "(\n  sum(rate(nginx_ingress_controller_requests{status=~\"5..\"}[5m]))\n/\n  sum(rate(nginx_ingress_controller_requests[5m]))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Total (User + System)",
   "type": "timeseries",
   "description": "Total CPU usage per pod (user + system). \nMetric source: container_cpu_user_seconds_total + container_cpu_system_seconds_total.\nUnit: cores (vCPU). Rate: 5 minutes.\n",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(\n    container_cpu_user_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", container!=\"POD\"}[5m]\n    +\n    container_cpu_system_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\"$service.*\", container!=\"POD\"}[5m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application CPU Usage (per Pod)",
   "type": "timeseries",
   "description": "Shows real-time CPU consumption per Pod in the selected cluster, namespace and service.\nCalculation: sum(rate(container_cpu_user_seconds_total + container_cpu_system_seconds_total)[5m]).\nUnit: CPU cores. Useful for performance analysis, HPA tuning and pod-level troubleshooting.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (pod) (\n  rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\"}[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Displays the current memory working set of pods matching the selected service ($service) in the selected namespace. Based on container_memory_working_set_bytes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  container_memory_working_set_bytes{\n    namespace=\"$namespace\",\n    pod=~\"$service.*\",\n    container!=\"POD\",\n    container!=\"\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}