{
 "title": "Environment Details",
 "tags": [ "environment" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\".*-api\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Services OK",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(count(kube_deployment_status_replicas_ready{namespace=~\"$${env}-(api|cms|frontend|services)\"} >= kube_deployment_spec_replicas{namespace=~\"$${env}-(api|cms|frontend|services)\"}) or vector(0)) + (count(kube_statefulset_status_replicas_ready{namespace=~\"$${env}-(api|cms|frontend|services)\"} >= kube_statefulset_replicas{namespace=~\"$${env}-(api|cms|frontend|services)\"}) or vector(0))",
     "legendFormat": "OK"
    }
   ]
  },
  {
   "title": "Services FAILED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(count(kube_deployment_status_replicas_ready{namespace=~\"$${env}-(api|cms|frontend|services)\"} < kube_deployment_spec_replicas{namespace=~\"$${env}-(api|cms|frontend|services)\"}) or vector(0)) + (count(kube_statefulset_status_replicas_ready{namespace=~\"$${env}-(api|cms|frontend|services)\"} < kube_statefulset_replicas{namespace=~\"$${env}-(api|cms|frontend|services)\"}) or vector(0))",
     "legendFormat": "FAILED"
    }
   ]
  },
  {
   "title": "Pod Restarts (1h)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"$${env}-(api|cms|frontend|services)\"}[1h])) or vector(0)",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (namespace) (kube_pod_info{namespace=~\"$${env}-(api|cms|frontend|services)\"}))",
     "legendFormat": "Namespaces"
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 36, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "label_replace(\n  kube_deployment_status_replicas_ready{\n    namespace=~\"$${env}-(api|cms|frontend|services)\",\n    deployment!~\".*job.*|.*prometheus.*|.*kube-state.*\"\n  },\n  \"service\", \"$1\", \"deployment\", \"(.*)\"\n) or label_replace(\n  kube_statefulset_status_replicas_ready{\n    namespace=~\"$${env}-(api|cms|frontend|services)\"\n  },\n  \"service\", \"$1\", \"statefulset\", \"(.*)\"\n)"
    },
    {
     "expr": "label_replace(\n  kube_deployment_spec_replicas{\n    namespace=~\"$${env}-(api|cms|frontend|services)\",\n    deployment!~\".*job.*|.*prometheus.*|.*kube-state.*\"\n  },\n  \"service\", \"$1\", \"deployment\", \"(.*)\"\n) or label_replace(\n  kube_statefulset_replicas{\n    namespace=~\"$${env}-(api|cms|frontend|services)\"\n  },\n  \"service\", \"$1\", \"statefulset\", \"(.*)\"\n)"
    },
    {
     "expr": "(\n  label_replace(\n    kube_deployment_status_replicas_ready{namespace=~\"$${env}-(api|cms|frontend|services)\",deployment!~\".*job.*|.*prometheus.*|.*kube-state.*\"},\n    \"service\", \"$1\", \"deployment\", \"(.*)\"\n  ) >= bool label_replace(\n    kube_deployment_spec_replicas{namespace=~\"$${env}-(api|cms|frontend|services)\",deployment!~\".*job.*|.*prometheus.*|.*kube-state.*\"},\n    \"service\", \"$1\", \"deployment\", \"(.*)\"\n  )\n) * on(namespace, service) group_left() (\n  label_replace(\n    kube_deployment_spec_replicas{namespace=~\"$${env}-(api|cms|frontend|services)\",deployment!~\".*job.*|.*prometheus.*|.*kube-state.*\"} > bool 0,\n    \"service\", \"$1\", \"deployment\", \"(.*)\"\n  )\n)\nor\n(\n  label_replace(\n    kube_statefulset_status_replicas_ready{namespace=~\"$${env}-(api|cms|frontend|services)\"},\n    \"service\", \"$1\", \"statefulset\", \"(.*)\"\n  ) >= bool label_replace(\n    kube_statefulset_replicas{namespace=~\"$${env}-(api|cms|frontend|services)\"},\n    \"service\", \"$1\", \"statefulset\", \"(.*)\"\n  )\n) * on(namespace, service) group_left() (\n  label_replace(\n    kube_statefulset_replicas{namespace=~\"$${env}-(api|cms|frontend|services)\"} > bool 0,\n    \"service\", \"$1\", \"statefulset\", \"(.*)\"\n  )\n)\nor\nmax by (namespace, service) (\n  label_replace(\n    kube_pod_status_phase{namespace=~\"$${env}-(api|cms|frontend|services)\", phase=\"Succeeded\"},\n    \"service\", \"$1\", \"pod\",\n    \"^([a-z0-9][a-z0-9.-]+[a-z0-9])-[0-9]+-[a-z0-9]+$\"\n  )\n) * 2"
    },
    {
     "expr": "(\n  max by (namespace, service) (\n    label_replace(\n      time() - kube_pod_start_time{\n        namespace=~\"$${env}-(api|cms|frontend|services)\",\n        pod!~\".*prometheus.*|.*kube-state.*|.*migration.*|.*job.*\"\n      },\n      \"service\", \"$1\", \"pod\",\n      \"^([a-z0-9][a-z0-9.-]+[a-z0-9])-[a-z0-9]{5,10}-[a-z0-9]{5}$\"\n    )\n  ) > 0\n) or (\n  max by (namespace, service) (\n    label_replace(\n      time() - kube_pod_start_time{\n        namespace=~\"$${env}-(api|cms|frontend|services)\",\n        pod!~\".*prometheus.*|.*kube-state.*|.*migration.*|.*job.*\"\n      },\n      \"service\", \"$1\", \"pod\",\n      \"^([a-z0-9][a-z0-9-]+)-[0-9]+$\"\n    )\n  ) > 0\n) or (\n  max by (namespace, service) (\n    label_replace(\n      time() - kube_pod_start_time{\n        namespace=~\"$${env}-(api|cms|frontend|services)\",\n        pod!~\".*prometheus.*|.*kube-state.*|.*migration.*|.*job.*\"\n      },\n      \"service\", \"$1\", \"pod\",\n      \"^([a-z0-9][a-z0-9.-]+[a-z0-9])-[0-9]+-[a-z0-9]+$\"\n    )\n  ) > 0\n)"
    },
    {
     "expr": "sum by (namespace, service) (\n  label_replace(\n    increase(\n      kube_pod_container_status_restarts_total{\n        namespace=~\"$${env}-(api|cms|frontend|services)\",\n        pod!~\".*prometheus.*|.*kube-state.*|.*migration.*|.*job.*\"\n      }[1h]\n    ),\n    \"service\", \"$1\", \"pod\",\n    \"^([a-z0-9][a-z0-9.-]+[a-z0-9])-[a-z0-9]{5,10}-[a-z0-9]{5}$\"\n  )\n) > -1\nor\nsum by (namespace, service) (\n  label_replace(\n    increase(\n      kube_pod_container_status_restarts_total{\n        namespace=~\"$${env}-(api|cms|frontend|services)\",\n        pod!~\".*prometheus.*|.*kube-state.*|.*migration.*|.*job.*\"\n      }[1h]\n    ),\n    \"service\", \"$1\", \"pod\",\n    \"^([a-z0-9][a-z0-9-]+)-[0-9]+$\"\n  )\n) > -1\nor\nsum by (namespace, service) (\n  label_replace(\n    increase(\n      kube_pod_container_status_restarts_total{\n        namespace=~\"$${env}-(api|cms|frontend|services)\",\n        pod!~\".*prometheus.*|.*kube-state.*|.*migration.*|.*job.*\"\n      }[1h]\n    ),\n    \"service\", \"$1\", \"pod\",\n    \"^([a-z0-9][a-z0-9.-]+[a-z0-9])-[0-9]+-[a-z0-9]+$\"\n  )\n) > -1"
    },
    {
     "expr": "(\n  label_replace(\n    kube_deployment_spec_replicas{\n      namespace=~\"$${env}-api\",\n      deployment!~\".*job.*|.*prometheus.*|.*kube-state.*\"\n    } * 0 + 1,\n    \"service\", \"$1\", \"deployment\", \"(.*)\"\n  )\n  or\n  label_replace(\n    kube_statefulset_replicas{namespace=~\"$${env}-api\"} * 0 + 1,\n    \"service\", \"$1\", \"statefulset\", \"(.*)\"\n  )\n)\nor\n(\n  label_replace(\n    kube_deployment_spec_replicas{\n      namespace=~\"$${env}-frontend\",\n      deployment!~\".*job.*|.*prometheus.*|.*kube-state.*\"\n    } * 0 + 2,\n    \"service\", \"$1\", \"deployment\", \"(.*)\"\n  )\n  or\n  label_replace(\n    kube_statefulset_replicas{namespace=~\"$${env}-frontend\"} * 0 + 2,\n    \"service\", \"$1\", \"statefulset\", \"(.*)\"\n  )\n)\nor\n(\n  label_replace(\n    kube_deployment_spec_replicas{\n      namespace=~\"$${env}-cms\",\n      deployment!~\".*job.*|.*prometheus.*|.*kube-state.*\"\n    } * 0 + 3,\n    \"service\", \"$1\", \"deployment\", \"(.*)\"\n  )\n  or\n  label_replace(\n    kube_statefulset_replicas{namespace=~\"$${env}-cms\"} * 0 + 3,\n    \"service\", \"$1\", \"statefulset\", \"(.*)\"\n  )\n  or\n  max by (namespace, service) (\n    label_replace(\n      kube_pod_status_phase{namespace=~\"$${env}-cms\", phase=\"Succeeded\"} * 0 + 3,\n      \"service\", \"$1\", \"pod\",\n      \"^([a-z0-9][a-z0-9.-]+[a-z0-9])-[0-9]+-[a-z0-9]+$\"\n    )\n  )\n)"
    }
   ]
  }
 ]
}