{
 "title": "Environment Status Overview",
 "tags": [ "environment" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Environments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(label_replace(\n  (\n    2 * (\n      1 -\n      min by (env) (\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-api\",\n                pod=~\"heimdall-.*|iris-.*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n            )\n          )\n        )\n        or\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n                pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n            )\n          )\n        )\n        or\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n                pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n            )\n          )\n        )\n      )\n    )\n  )\n  +\n  on(env)\n  (\n    min by (env) (\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-api\",\n              pod=~\"heimdall-.*|iris-.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n          )\n        )\n      )\n      or\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n              pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n          )\n        )\n      )\n      or\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n              pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n          )\n        )\n      )\n    )\n    *\n    (\n      (\n        max by (env) (\n          label_replace(\n            kube_job_status_failed{\n              namespace=~\"(kan-[0-9]+|dev|test)-(api|cms|frontend)\",\n              job_name=~\".*backup.*|.*dump.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-(api|cms|frontend)\"\n          )\n        )\n      )\n      or on(env)\n      (\n        0 *\n        min by (env) (\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-api\",\n                  pod=~\"heimdall-.*|iris-.*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n              )\n            )\n          )\n          or\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n                  pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n              )\n            )\n          )\n          or\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n                  pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n              )\n            )\n          )\n        )\n      )\n    )\n  ),\n  \"service\", \"STATUS\", \"\", \"\"\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OK",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((label_replace(\n  (\n    2 * (\n      1 -\n      min by (env) (\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-api\",\n                pod=~\"heimdall-.*|iris-.*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n            )\n          )\n        )\n        or\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n                pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n            )\n          )\n        )\n        or\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n                pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n            )\n          )\n        )\n      )\n    )\n  )\n  +\n  on(env)\n  (\n    min by (env) (\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-api\",\n              pod=~\"heimdall-.*|iris-.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n          )\n        )\n      )\n      or\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n              pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n          )\n        )\n      )\n      or\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n              pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n          )\n        )\n      )\n    )\n    *\n    (\n      (\n        max by (env) (\n          label_replace(\n            kube_job_status_failed{\n              namespace=~\"(kan-[0-9]+|dev|test)-(api|cms|frontend)\",\n              job_name=~\".*backup.*|.*dump.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-(api|cms|frontend)\"\n          )\n        )\n      )\n      or on(env)\n      (\n        0 *\n        min by (env) (\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-api\",\n                  pod=~\"heimdall-.*|iris-.*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n              )\n            )\n          )\n          or\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n                  pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n              )\n            )\n          )\n          or\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n                  pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n              )\n            )\n          )\n        )\n      )\n    )\n  ),\n  \"service\", \"STATUS\", \"\", \"\"\n)) == 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WARNING",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((label_replace(\n  (\n    2 * (\n      1 -\n      min by (env) (\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-api\",\n                pod=~\"heimdall-.*|iris-.*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n            )\n          )\n        )\n        or\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n                pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n            )\n          )\n        )\n        or\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n                pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n            )\n          )\n        )\n      )\n    )\n  )\n  +\n  on(env)\n  (\n    min by (env) (\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-api\",\n              pod=~\"heimdall-.*|iris-.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n          )\n        )\n      )\n      or\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n              pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n          )\n        )\n      )\n      or\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n              pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n          )\n        )\n      )\n    )\n    *\n    (\n      (\n        max by (env) (\n          label_replace(\n            kube_job_status_failed{\n              namespace=~\"(kan-[0-9]+|dev|test)-(api|cms|frontend)\",\n              job_name=~\".*backup.*|.*dump.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-(api|cms|frontend)\"\n          )\n        )\n      )\n      or on(env)\n      (\n        0 *\n        min by (env) (\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-api\",\n                  pod=~\"heimdall-.*|iris-.*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n              )\n            )\n          )\n          or\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n                  pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n              )\n            )\n          )\n          or\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n                  pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n              )\n            )\n          )\n        )\n      )\n    )\n  ),\n  \"service\", \"STATUS\", \"\", \"\"\n)) == 1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FAILED",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((label_replace(\n  (\n    2 * (\n      1 -\n      min by (env) (\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-api\",\n                pod=~\"heimdall-.*|iris-.*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n            )\n          )\n        )\n        or\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n                pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n            )\n          )\n        )\n        or\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n                pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n            )\n          )\n        )\n      )\n    )\n  )\n  +\n  on(env)\n  (\n    min by (env) (\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-api\",\n              pod=~\"heimdall-.*|iris-.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n          )\n        )\n      )\n      or\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n              pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n          )\n        )\n      )\n      or\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n              pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n          )\n        )\n      )\n    )\n    *\n    (\n      (\n        max by (env) (\n          label_replace(\n            kube_job_status_failed{\n              namespace=~\"(kan-[0-9]+|dev|test)-(api|cms|frontend)\",\n              job_name=~\".*backup.*|.*dump.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-(api|cms|frontend)\"\n          )\n        )\n      )\n      or on(env)\n      (\n        0 *\n        min by (env) (\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-api\",\n                  pod=~\"heimdall-.*|iris-.*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n              )\n            )\n          )\n          or\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n                  pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n              )\n            )\n          )\n          or\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n                  pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n              )\n            )\n          )\n        )\n      )\n    )\n  ),\n  \"service\", \"STATUS\", \"\", \"\"\n)) == 2) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts (1h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(round(\n  sum by (env) (\n    label_replace(\n      increase(kube_pod_container_status_restarts_total{\n        namespace=~\"(kan-[0-9]+|dev|test)-(api|cms|frontend)\",\n        container!=\"\",\n        container!=\"POD\",\n        pod=~\"heimdall-.*|iris-.*|api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*|betting-.*|nuxt-.*|websockets-.*\"\n      }[1h]),\n      \"env\", \"$1\",\n      \"namespace\", \"(kan-[0-9]+|dev|test)-.*\"\n    )\n  )\n))) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Environment Status Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace(\n  min by (env) (\n    label_replace(\n      kube_pod_status_ready{\n        condition=\"true\",\n        namespace=~\"(kan-[0-9]+|dev|test)-api\",\n        pod=~\"heimdall-.*|iris-.*\"\n      },\n      \"env\", \"$1\",\n      \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n    )\n  ),\n  \"service\", \"API\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n  min by (env) (\n    label_replace(\n      kube_pod_status_ready{\n        condition=\"true\",\n        namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n        pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n      },\n      \"env\", \"$1\",\n      \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n    )\n  ),\n  \"service\", \"CMS\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n  min by (env) (\n    label_replace(\n      kube_pod_status_ready{\n        condition=\"true\",\n        namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n        pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n      },\n      \"env\", \"$1\",\n      \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n    )\n  ),\n  \"service\", \"FRONTEND\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n  (\n    2 * (\n      1 -\n      min by (env) (\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-api\",\n                pod=~\"heimdall-.*|iris-.*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n            )\n          )\n        )\n        or\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n                pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n            )\n          )\n        )\n        or\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n                pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n            )\n          )\n        )\n      )\n    )\n  )\n  +\n  on(env)\n  (\n    min by (env) (\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-api\",\n              pod=~\"heimdall-.*|iris-.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n          )\n        )\n      )\n      or\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n              pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n          )\n        )\n      )\n      or\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n              pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n          )\n        )\n      )\n    )\n    *\n    (\n      (\n        max by (env) (\n          label_replace(\n            kube_job_status_failed{\n              namespace=~\"(kan-[0-9]+|dev|test)-(api|cms|frontend)\",\n              job_name=~\".*backup.*|.*dump.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-(api|cms|frontend)\"\n          )\n        )\n      )\n      or on(env)\n      (\n        0 *\n        min by (env) (\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-api\",\n                  pod=~\"heimdall-.*|iris-.*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n              )\n            )\n          )\n          or\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n                  pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n              )\n            )\n          )\n          or\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n                  pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n              )\n            )\n          )\n        )\n      )\n    )\n  ),\n  \"service\", \"STATUS\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n  (\n    round(\n  sum by (env) (\n    label_replace(\n      increase(kube_pod_container_status_restarts_total{\n        namespace=~\"(kan-[0-9]+|dev|test)-(api|cms|frontend)\",\n        container!=\"\",\n        container!=\"POD\",\n        pod=~\"heimdall-.*|iris-.*|api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*|betting-.*|nuxt-.*|websockets-.*\"\n      }[1h]),\n      \"env\", \"$1\",\n      \"namespace\", \"(kan-[0-9]+|dev|test)-.*\"\n    )\n  )\n)\n    or on(env)\n    (\n      0 * (label_replace(\n  (\n    2 * (\n      1 -\n      min by (env) (\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-api\",\n                pod=~\"heimdall-.*|iris-.*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n            )\n          )\n        )\n        or\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n                pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n            )\n          )\n        )\n        or\n        (\n          min by (env) (\n            label_replace(\n              kube_pod_status_ready{\n                condition=\"true\",\n                namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n                pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n              },\n              \"env\", \"$1\",\n              \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n            )\n          )\n        )\n      )\n    )\n  )\n  +\n  on(env)\n  (\n    min by (env) (\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-api\",\n              pod=~\"heimdall-.*|iris-.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n          )\n        )\n      )\n      or\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n              pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n          )\n        )\n      )\n      or\n      (\n        min by (env) (\n          label_replace(\n            kube_pod_status_ready{\n              condition=\"true\",\n              namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n              pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n          )\n        )\n      )\n    )\n    *\n    (\n      (\n        max by (env) (\n          label_replace(\n            kube_job_status_failed{\n              namespace=~\"(kan-[0-9]+|dev|test)-(api|cms|frontend)\",\n              job_name=~\".*backup.*|.*dump.*\"\n            },\n            \"env\", \"$1\",\n            \"namespace\", \"(kan-[0-9]+|dev|test)-(api|cms|frontend)\"\n          )\n        )\n      )\n      or on(env)\n      (\n        0 *\n        min by (env) (\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-api\",\n                  pod=~\"heimdall-.*|iris-.*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-api\"\n              )\n            )\n          )\n          or\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-cms\",\n                  pod=~\"api-.*|backend-.*|frontend-.*|rest-.*|nginx-.*|mysql-0|postgresql-0|rabbitmq-0|redis-master-0|redis-replicas-0|memcached-.*|phpmyadmin-.*|worker\\\\..*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-cms\"\n              )\n            )\n          )\n          or\n          (\n            min by (env) (\n              label_replace(\n                kube_pod_status_ready{\n                  condition=\"true\",\n                  namespace=~\"(kan-[0-9]+|dev|test)-frontend\",\n                  pod=~\"betting-.*|nuxt-.*|websockets-.*\"\n                },\n                \"env\", \"$1\",\n                \"namespace\", \"(kan-[0-9]+|dev|test)-frontend\"\n              )\n            )\n          )\n        )\n      )\n    )\n  ),\n  \"service\", \"STATUS\", \"\", \"\"\n))\n    )\n  ),\n  \"service\", \"RESTARTS (1H)\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}