{
 "title": "Infrastructure Application Metrics",
 "tags": [ "application" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "EKS Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_memory_working_set_bytes{cluster=\"$cluster_name\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container restarts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{container=\"$container\", cluster=\"$cluster_name\"}[$__range])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Percentage of CPU request",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"$container\", cluster=\"$cluster_name\"}[5m])) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{container=\"$container\", cluster=\"$cluster_name\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"$container\", cluster=\"$cluster_name\"}[5m])) by (pod) / sum(kube_pod_container_resource_requests{container=\"$container\", cluster=\"$cluster_name\", resource=\"cpu\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Percent of memory requested",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(100 * sum(container_memory_working_set_bytes{cluster=\"$cluster_name\", container=\"$container\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{container=\"$container\", cluster=\"$cluster_name\"}) by (pod))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "round(100 * sum(container_memory_working_set_bytes{cluster=\"$cluster_name\", container=\"$container\"}) by (pod) / sum(kube_pod_container_resource_requests{container=\"$container\", cluster=\"$cluster_name\", resource=\"memory\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage (Milicores)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster_name\", container=\"$container\"}",
     "legendFormat": "{{pod}} requested"
    },
    {
     "expr": "irate(container_cpu_usage_seconds_total{cluster=\"$cluster_name\", container=\"$container\"}[5m])",
     "legendFormat": "{{pod}} current"
    },
    {
     "expr": "kube_pod_container_resource_requests{cluster=\"$cluster_name\", container=\"$container\", resource=\"cpu\"}",
     "legendFormat": "{{pod}} requested"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster_name\", container=\"$container\"}) by (container)",
     "legendFormat": "{{container}} limit"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster_name\", container=\"$container\"}",
     "legendFormat": "{{pod}} requested"
    },
    {
     "expr": "container_memory_working_set_bytes{cluster=\"$cluster_name\", container=\"$container\"}",
     "legendFormat": "{{pod}} actual"
    },
    {
     "expr": "kube_pod_container_resource_requests{cluster=\"$cluster_name\", container=\"$container\", resource=\"memory\"}",
     "legendFormat": "{{pod}} requested"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{cluster=\"$cluster_name\", container=\"$container\", resource=\"memory\"}) by (container)",
     "legendFormat": "{{container}} limit"
    }
   ]
  }
 ]
}