@type elasticsearch
@include /etc/fluent/common.d/.es_connect.conf

logstash_format true
logstash_prefix ${prefix}
logstash_dateformat %Y.%m.%d
rollover_index true

# Customizing index template
template_name ${prefix}
template_file "/etc/fluent/templates/fluentd-es-template-apps.json"

<buffer prefix>
  @type memory
  @include /etc/fluent/common.d/.buffer.conf
</buffer>
