---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-vpn
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: ${efs_id}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-vpn
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  volumeName: efs-vpn
  storageClassName: ""
