  flush_mode interval
  retry_type exponential_backoff
  flush_thread_count 3
  flush_interval 10s
  retry_forever true
  retry_wait 5s
  retry_max_interval 60s
  chunk_limit_size 16m
  total_limit_size 512m
  queue_limit_length 64
  overflow_action block
