@log_level info

host "#{ENV['ES_HOST'] || 'elasticsearch-es-http.eko-stack.svc'}"
port "#{ENV['ES_PORT'] || 9200}"
user "#{ENV['ES_USER'] || 'elastic'}"
password "#{ENV['elastic']}"
scheme 'https'
ssl_verify 'false'

reconnect_on_error true
reload_on_failure true

reload_connections false

request_timeout 120s

log_es_400_reason true
# # avoid 7.x errors
suppress_type_name true

# # setting sniffer class
# sniffer_class_name Fluent::Plugin::ElasticsearchSimpleSniffer
# sniffer_class_name Fluent::Plugin::ElasticsearchDefaultSniffer

logstash_format false
include_tag_key true
time_key time
include_timestamp true

# # Customizing index template
use_legacy_template false
template_overwrite true

rollover_index true
index_date_pattern ''
enable_ilm true

ilm_policy_overwrite false

#<label @FLUENT_LOG>
#  <match **>
#    @type stdout
#    @id output_to_stdout
#    # format json
#    <buffer>
#      flush_interval 10s
#    </buffer>
#  </match>
#</label>
