send_timeout 120s
recover_wait 20s
hard_timeout 120s
<server>
  name "#{ENV['FS_NAME'] || 'fluentd-tools'}"
  host "#{ENV['FS_HOST'] || 'fluentd.tools.int'}"
  port "#{ENV['FS_PORT'] || 24226}"
  weight 60
</server>
