# UDP input to receive logs from the applications
<source>
  @type udp
  tag activity.log
  port 24224
  bind 0.0.0.0
  <parse>
    @type json
    time_key @timestamp
    time_type unixtime
    # time_format %s%L
  </parse>
</source>
