apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-elasticsearch-exporter
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: prometheus-elasticsearch-exporter
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-elasticsearch-exporter-5.0.0
    helm.toolkit.fluxcd.io/name: prometheus-elasticsearch-exporter
    helm.toolkit.fluxcd.io/namespace: monitoring
    heritage: Helm
    release: kube-prometheus-stack
  name: prometheus-elasticsearch-exporter
  namespace: monitoring
spec:
  endpoints:
  - honorLabels: true
    interval: 10s
    path: /metrics
    port: http
    scheme: http
    scrapeTimeout: 10s
  jobLabel: prometheus-elasticsearch-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  sampleLimit: 0
  selector:
    matchLabels:
      app: prometheus-elasticsearch-exporter
      release: prometheus-elasticsearch-exporter

