---
apiVersion: 'v1'
kind: 'ConfigMap'
metadata:
  name: 'kyverno-values'
  # namespace: 'flux-system'
data:
  values.yaml: |
    admissionController:
      replicas: 3
      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
              - '*'
              resources:
              - '*'
              verbs:
              - get
              - list
              - watch

    backgroundController:
      replicas: 2
    cleanupController:
      replicas: 2
    reportsController:
      replicas: 2
    global:
      tolerations:
        - key: pool
          value: infra
          operator: Equal
          effect: NoSchedule
