---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: vmalert-persistent
  namespace: monitoring
  labels:
    owner: devops
    stream: devops
    env: ${env}
    product: observability
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vmalert-persistent
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization
