---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  namespace: monitoring
  name: prometheus-general-rules
  labels:
    owner: devops
    stream: devops
    env: ${env}
    product: observability
    temporary: "false"
    deleteAfter: "false"
    vmrules: prometheus-general-rules
spec:
  groups:
    - name: kube-prometheus-general.rules
      rules:
        - expr: count without(instance, pod, node) (up == 1)
          record: count:up1
        - expr: count without(instance, pod, node) (up == 0)
          record: count:up0
