---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aws-elasticache.yaml
  - aws-rabbitmq.yaml
  - aws-rds.yaml
  # - kube_state_metrics_rules.yaml
  - victoria-metrics.yaml
  # - gitlab-live-alerts.yaml
  - gameserver-blackbox.yaml
  - blackbox-tls-certs-expire.yaml
  - opensearch.yaml
