---
apiVersion: v1
kind: Service
metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    app: kube-proxy
    jobLabel: kube-proxy
    owner: devops
    stream: devops
    env: ${env}
    product: observability
    temporary: "false"
    deleteAfter: "false"
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10249
      protocol: TCP
      targetPort: 10249
  selector:
    k8s-app: kube-proxy
  type: ClusterIP
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-proxy
  namespace: monitoring
  labels:
    app: kube-proxy
    owner: devops
    stream: devops
    env: ${env}
    vmservicescrape: kube-proxy
    product: observability
    temporary: "false"
    deleteAfter: "false"
spec:
  selector:
    matchLabels:
      app: kube-proxy
      jobLabel: kube-proxy
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
    - port: http-metrics
      scheme: http
      metricRelabelConfigs:
        - sourceLabels: [__name__]
          regex: (kubernetes_feature_enabled|rest_client_rate_limiter_duration_seconds_bucket)
          action: drop
  jobLabel: jobLabel
