---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alb-controller
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: base
  path: infra/aws-loadbalancer-controller
  targetNamespace: kube-system
  force: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: alb-ingress
      namespace: kube-system
    - apiVersion: apps/v1
      kind: Deployment
      name: alb-controler-aws-load-balancer-controller
      namespace: kube-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: terraform-to-flux-bridge
        optional: true
