---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kustomize-controller-helm-manager
rules:
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["autoscaling.ginsp.net"]
    resources: ["consistentconsumerautoscalers"]
    verbs: ["get", "list", "watch"]
