---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secret-generator
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  dependsOn:
    - name: kyverno
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: base
    namespace: flux-system
  path: services/secret-generator
  force: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kubernetes-secret-generator
      namespace: flux-system
    - apiVersion: apps/v1
      kind: Deployment
      name: kubernetes-secret-generator
      namespace: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: terraform-to-flux-bridge
        optional: true
