---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: vminsert-vmcluster-persistent
  namespace: monitoring
  labels:
    app: vminsert
    env: ${env}
    owner: devops
    stream: devops
    product: observability
    temporary: "false"
    deleteAfter: "false"
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vminsert-vmcluster-persistent
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization
