---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubecost-cost-analyzer
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 32Gi
  hostPath:
    path: /
