---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubecost
  namespace: services
spec:
  releaseName: kubecost
  chart:
    spec:
      chart: cost-analyzer
      sourceRef:
        kind: HelmRepository
        name: cost-analyzer
        namespace: flux-system
      version: 2.5.1
  interval: 5h
  install:
    remediation:
      retries: 3
    timeout: 10m
  values:
    tolerations:
      - effect: NoSchedule
        key: pool
        operator: Equal
        value: infra
    global:
      grafana:
        enabled: false
        proxy: false
      prometheus:
        enabled: false
        fqdn: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
    pricingCsv:
      enabled: false
    nodeSelector: {}
    networkPolicy:
      enabled: false
    podSecurityPolicy:
      enabled: false
    kubecostFrontend:
      image: public.ecr.aws/kubecost/frontend
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "10m"
          memory: "55Mi"
    kubecostModel:
      image: public.ecr.aws/kubecost/cost-model
      imagePullPolicy: Always
      warmCache: true
      warmSavingsCache: true
      etl: true
      # The total number of days the ETL storage will build
      etlStoreDurationDays: 120
      maxQueryConcurrency: 5
      utcOffset: "+00:00"
      resources:
        requests:
          cpu: "200m"
          memory: "55Mi"
    serviceAccount:
      create: true
    persistentVolume:
      size: 32Gi
      dbSize: 32.0Gi
      enabled: true
      storageClass: ""
      existingClaim: kubecost-cost-analyzer
    ingress:
      enabled: true
      className: public-shared
      # annotations:
        #kubernetes.io/ingress.class: nginx
        #kubernetes.io/tls-acme: "true"
      paths: ["/"]
      hosts:
        - kubecost.common.demo-platform.ca
      tls: []
      #  - secretName: cost-analyzer-tls
      #    hosts:
      #      - cost-analyzer.local

    service:
      type: ClusterIP
      port: 9090
      targetPort: 9090

    prometheus:
      server:
        image:
          repository: public.ecr.aws/kubecost/prometheus
          tag: v2.35.0
        resources: {}
        global:
          scrape_interval: 1m
          scrape_timeout: 10s
          evaluation_interval: 1m
          external_labels:
            cluster_id: cluster-one 
        persistentVolume:
          size: 32Gi
          enabled: true
        extraArgs:
          query.max-concurrency: 1
          query.max-samples: 100000000
        tolerations: []

      configmapReload:
        prometheus:
          enabled: false
      kube-state-metrics:
        disabled: false
      nodeExporter:
        enabled: false
    reporting:
      productAnalytics: false

    networkCosts:
      enabled: true
      
    serviceMonitor: 
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
      metricRelabelings: []
      relabelings: []
      networkCosts:
        enabled: true
        scrapeTimeout: 10s
        additionalLabels:
          release: kube-prometheus-stack
        metricRelabelings: []
        relabelings: []

    prometheusRule:
      enabled: true
